services:
  axonserver:
    image: axoniq/axonserver
    volumes:
      - ./axonserver-data:/data
      - ./axonserver-events:/eventdata
      - ./axonserver-config:/config
    ports:
      - '8024:8024'
      - '8124:8124'